#+TITLE: Programação distribuída e paralela - Trabalho OpenMP
#+AUTHOR: Leonardo Heisler, Thiago dos Santos Gonçalves e Vinícius Daniel
#+DATE: \today
#+LATEX_CLASS: article
#+LATEX_HEADER: \hypersetup{colorlinks=true, linkcolor=blue, urlcolor=blue}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{indentfirst}
#+LATEX_HEADER: \usepackage{float}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \setminted{frame=single,linenos=true,breaklines=true}

#+LATEX: \clearpage

* Experimentos

Primeiramente, vamos começar iterando sobre os experimentos executados.
Analisemos o arquivo que descreve alguns dos experimentos a serem executados:

#+NAME: experiments
#+begin_src R :results value :colnames yes :exports results
  library(tidyverse)
  read.csv(here::here("experiments.csv")) |>
    slice_head(n = 15)
#+end_src

#+RESULTS: experiments
| Resolution | Otimization | Samples | Threads | Blocks |
|------------+-------------+---------+---------+--------|
|  3840x2160 | collapse    |      30 |      20 |    0.1 |
|  3840x2160 | samples     |      30 |       1 |    0.1 |
|    640x480 | collapse    |      30 |       1 |    0.1 |
|    640x480 | tasks       |     900 |      20 |    0.1 |
|    640x480 | tasks       |     900 |       1 |    0.1 |
|  3840x2160 | tasks       |     900 |      40 |    0.1 |
|  3840x2160 | tasks       |      30 |      20 |    0.1 |
|    640x480 | samples     |      30 |      40 |    0.1 |
|    640x480 | collapse    |     900 |      20 |    0.1 |
|  3840x2160 | samples     |     900 |      40 |    0.1 |
|    640x480 | samples     |     900 |      20 |    0.1 |
|  3840x2160 | collapse    |      30 |      40 |    0.1 |
|  3840x2160 | samples     |     900 |       1 |    0.1 |
|  3840x2160 | samples     |     900 |      20 |    0.1 |
|    640x480 | collapse    |     900 |      40 |    0.1 |

Observamos aqui os fatores dos experimentos:
1. *Resolução*: $3840 \times 2160$ e $640 \times 480$.
2. *Otimização*: paralelismo a nível da imagem, a nível das /samples/ e com tarefas.
3. *Número de /samples/*: 30 e 900.
4. *Quantidade de /threads/*: 1, 20 e 40.

Ademais, nota-se que foram utilizadas *2* replicações para cada experimento, totalizando *3* execuções por combinação de fatores.

Finalmente, os experimentos foram executados na máquina *hype5* do PCAD, com uma estrutura de diretórios definida em função dos fatores.

#+LATEX: \clearpage

* Resultados

Primeiramente, vamos utilizar a linguagem *R* para colocar todos os dados em uma tabela.

Em seguida, vamos visualizar alguns dos dados.

#+NAME: results_join
#+begin_src R :results value table :exports results :colnames yes :session
  library(tidyverse)
  experiments <- read_csv(here::here("experiments.csv"))

  read_row_data <- function(Resolution, Otimization, Samples, Threads, Blocks) {
    dir_path <- here::here(paste0("experiments", "/", Resolution, "/", Otimization, "/", Samples, "/", Threads, "/", Blocks))
    stdout_path <- paste0(dir_path, "/", "logs.out")
    stdout_lines <- readLines(stdout_path)
    render_line <- grep("Done rendering. Time:", stdout_lines, value = TRUE)
    time_str <- str_extract(render_line, "^Done rendering\\. Time: ([0-9.]+) seconds\\.$", group = 1)
    time_numeric <- as.numeric(time_str)
    vtune_path = paste0(dir_path, "/", "vtune_reports.csv")
    vtune_csv <- read_delim(vtune_path, delim = "\t", show_col_types = FALSE)

    vtune_csv |>
      select(`Metric Name`, `Metric Value`) |>
      filter(`Metric Name` %in% c("CPI Rate", "Average CPU Frequency", "Effective Physical Core Utilization", "Effective Logical Core Utilization", "Elapsed Time")) |>
      mutate(`Metric Name` = recode(`Metric Name`,
        "CPI Rate" = "CPI",
        "Average CPU Frequency" = "CPU",
        "Effective Physical Core Utilization" = "PC",
        "Effective Logical Core Utilization" = "LC",
        "Elapsed Time" = "Total time"
      )) |>
      mutate(`Metric Value` = case_when(
        `Metric Name` == "CPU" ~ round(as.numeric(`Metric Value`) / 1e9, digits = 3),
        `Metric Name` %in% c("PC", "LC") ~ as.numeric(str_extract(`Metric Value`, "^([^%])+%", group = 1)) / 100,
        TRUE ~ as.numeric(`Metric Value`)
      )) |>
      rename(`Metric` = "Metric Name") |>
      rename(`Value` = "Metric Value") |>
      add_row(`Metric` = "Calc. time", `Value` = round(time_numeric, digits = 3))
  }

  results <- experiments |>
                  mutate(`Blocks` = substring(Blocks, 3)) %>%
  		mutate(results = pmap(., read_row_data)) |>
  		unnest(results)
  results |>
    select(-`Blocks`) |>
    slice_head(n = 15)
#+end_src


#+ATTR_LATEX: :environment tabularx :booktabs t :width \textwidth
#+RESULTS: results_join
| Resolution | Otimization | Samples | Threads | Metric     |     Value |
|------------+-------------+---------+---------+------------+-----------|
|  3840x2160 | collapse    |      30 |      20 | Total time | 10.947427 |
|  3840x2160 | collapse    |      30 |      20 | CPI        |  0.512917 |
|  3840x2160 | collapse    |      30 |      20 | CPU        |     2.656 |
|  3840x2160 | collapse    |      30 |      20 | PC         |      0.07 |
|  3840x2160 | collapse    |      30 |      20 | LC         |      0.05 |
|  3840x2160 | collapse    |      30 |      20 | Calc. time |     8.303 |
|  3840x2160 | samples     |      30 |       1 | Total time | 85.500342 |
|  3840x2160 | samples     |      30 |       1 | CPI        |  0.500227 |
|  3840x2160 | samples     |      30 |       1 | CPU        |     2.987 |
|  3840x2160 | samples     |      30 |       1 | PC         |         0 |
|  3840x2160 | samples     |      30 |       1 | LC         |      0.05 |
|  3840x2160 | samples     |      30 |       1 | Calc. time |    82.642 |
|    640x480 | collapse    |      30 |       1 | Total time |  3.002269 |
|    640x480 | collapse    |      30 |       1 | CPI        |  0.479128 |
|    640x480 | collapse    |      30 |       1 | CPU        |     2.986 |

Agora que possuímos os dados de todas as execuções, podemos computar algumas agregações.


#+NAME: aggregations
#+begin_src R :results value :exports results :session :colnames yes
results |>
    group_by(`Metric`) |>
    summarise(`Mean` = round(mean(`Value`), digits = 3),
	    `Standard deviation` = round(sd(`Value`), digits = 3),
	    `Min` = round(min(`Value`), digits = 3),
	    `Max` = round(max(`Value`), digits = 3))
#+end_src

#+RESULTS: aggregations
| Metric     |    Mean | Standard deviation |   Min |      Max |
|------------+---------+--------------------+-------+----------|
| CPI        |   1.802 |              1.815 | 0.475 |    6.166 |
| CPU        |   2.733 |              0.181 | 2.594 |    2.989 |
| Calc. time | 310.435 |            661.401 | 0.274 | 2290.334 |
| LC         |   0.045 |              0.023 |     0 |     0.09 |
| PC         |   0.036 |              0.034 |     0 |     0.09 |
| Total time | 311.889 |            662.048 | 0.384 | 2293.335 |

Em seguida, alguns gráficos.

#+begin_src R :results value :exports none :session :colnames yes
  total_times <- results |>
    filter(`Metric` == "Total time") |>
    select(-`Metric`) |>
    group_by(`Resolution`, `Otimization`, `Samples`, `Threads`) |>
    summarise(`Value` = mean(`Value`))

  speed_ups <- total_times |>
    group_by(`Resolution`, `Otimization`, `Samples`) |>
    mutate(`Speedup` = `Value`[`Threads` == 1] / `Value`) |>
    select(-`Value`) |>
    filter(`Threads` > 1) |>
    ungroup()

  efficiencies <- speed_ups |>
    mutate(`Efficiency` = `Speedup` / `Threads`) |>
    select(-`Speedup`)
#+end_src

#+RESULTS:
| Resolution | Otimization | Samples | Threads |         Efficiency |
|------------+-------------+---------+---------+--------------------|
|  3840x2160 | collapse    |      30 |      20 |  0.361954632422185 |
|  3840x2160 | collapse    |      30 |      40 |  0.245291631457323 |
|  3840x2160 | collapse    |     900 |      20 |  0.475720810197091 |
|  3840x2160 | collapse    |     900 |      40 |  0.376469926685016 |
|  3840x2160 | samples     |      30 |      20 | 0.0423207524956456 |
|  3840x2160 | samples     |      30 |      40 | 0.0140397195163273 |
|  3840x2160 | samples     |     900 |      20 | 0.0747586925950843 |
|  3840x2160 | samples     |     900 |      40 | 0.0550217388374816 |
|  3840x2160 | tasks       |      30 |      20 | 0.0729530199572017 |
|  3840x2160 | tasks       |      30 |      40 | 0.0231940685225103 |
|  3840x2160 | tasks       |     900 |      20 |  0.482043378624323 |
|  3840x2160 | tasks       |     900 |      40 |  0.362179113548891 |
|    640x480 | collapse    |      30 |      20 |  0.283277801351709 |
|    640x480 | collapse    |      30 |      40 |  0.154935353236374 |
|    640x480 | collapse    |     900 |      20 |  0.466481365332397 |
|    640x480 | collapse    |     900 |      40 |  0.362125356151744 |
|    640x480 | samples     |      30 |      20 | 0.0458673572451764 |
|    640x480 | samples     |      30 |      40 | 0.0141972089219249 |
|    640x480 | samples     |     900 |      20 | 0.0798830003723476 |
|    640x480 | samples     |     900 |      40 | 0.0590780487805307 |
|    640x480 | tasks       |      30 |      20 | 0.0808556689083978 |
|    640x480 | tasks       |      30 |      40 | 0.0219751744996768 |
|    640x480 | tasks       |     900 |      20 |  0.487416516270381 |
|    640x480 | tasks       |     900 |      40 |  0.366582253998126 |

#+NAME: speedup
#+begin_src R :results graphics file :exports results :session :file speedup.pdf
  library(ggplot2)

  speed_ups$Samples <- as.factor(speed_ups$Samples)

  plot <- ggplot(speed_ups, aes(x = `Threads`, y = `Speedup`, color = `Resolution`, linetype = `Samples`)) +
    geom_line() +
    geom_point() +
    facet_wrap(~ `Otimization`, labeller = as_labeller(str_to_title), scales = "free_y") +
    theme_bw()
  ggsave(here::here("experiments/speedup.pdf"), plot = plot)
#+end_src

#+RESULTS: speedup
[[file:speedup.pdf]]

#+NAME: efficiency
#+begin_src R :results graphics file :exports results :session :file efficiency.pdf
  library(ggplot2)

  efficiencies$Samples <- as.factor(efficiencies$Samples)

  plot <- ggplot(efficiencies, aes(x = `Threads`, y = `Efficiency`, color = `Resolution`, linetype = `Samples`)) +
    geom_line() +
    geom_point() +
    facet_wrap(~ `Otimization`, labeller = as_labeller(str_to_title), scales = "free_y") +
    theme_bw()
  ggsave(here::here("experiments/efficiency.pdf"), plot = plot)
#+end_src

#+RESULTS: efficiency
[[file:efficiency.pdf]]

